- type: pointOfInterest
  parent: BaseMobilePOI
  id: BasePOI
  abstract: true
  addComponents:
  - type: ForceAnchor

# Mono

- type: pointOfInterest
  id: BaseMobilePOI
  abstract: true
  minimumDistance: 4000 # Some sane defaults
  maximumDistance: 8000
  spawnGamePreset: [ NFAdventure, NFPirate, MonoStandard, MonoRogueTSF, MonoRogueUSSP, MonoTSFUSSP, MonoADS, MonoChimera, MonoMixed, MonoAllAtOnce ] # Behold my list of gamerules
  spawnGroup: Optional
  addComponents:
  - type: IFF
    color: "#ffa600"
    readOnly: true
