using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mono.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class PointDiskConsoleMenu : FancyWindow
{

    public event Action? OnServerButtonPressed;

    public event Action? OnPrint1KButtonPressed;

    public event Action? OnPrint5KButtonPressed;

    public event Action? OnPrint10KButtonPressed;

    public PointDiskConsoleMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        Print1KButton.OnPressed += _ => OnPrint1KButtonPressed?.Invoke();
        Print5KButton.OnPressed += _ => OnPrint5KButtonPressed?.Invoke();
        Print10KButton.OnPressed += _ => OnPrint10KButtonPressed?.Invoke();
    }

    public void Update(PointDiskConsoleBoundUserInterfaceState state)
    {
        Print1KButton.Disabled = !state.CanPrint1K;
        Print5KButton.Disabled = !state.CanPrint5K;
        Print10KButton.Disabled = !state.CanPrint10K;
        TotalLabel.Text = Loc.GetString("point-disk-ui-total-label", ("amount", state.ServerPoints));
        Print1KButton.Text = Loc.GetString("point-disk-ui-print-1k-button", ("amount", state.PointCost1K));
        Print5KButton.Text = Loc.GetString("point-disk-ui-print-5k-button", ("amount", state.PointCost5K));
        Print10KButton.Text = Loc.GetString("point-disk-ui-print-10k-button", ("amount", state.PointCost10K));
    }
}

